= Distributed Switch Architecture testing

dsatest is a Linux user space network testing framework for Ethernet switches driven by the kernel space DSA framework.
It provides an extensive list of test cases, a command line to access the test bench and run the tests, as well as a Python API.
It supports many Ethernet switch chips and target machines.

== Getting started

These instructions will get you a copy of the project up and running on your local test bench.

=== Prerequisites

The framework depends on `python` and `python-paramiko`.

=== Installing

To get the source code of the dsatest framework, follow these steps:

[source,sh]
----
git clone git@github.com:d-k-c/dsatest.git
cd dsatest/
----

Ensure that the framework is functional by listing the tests and running the sanity tests:

[source,sh]
----
./dsatest -l -B bench.cfg.example
./dsatest --dry-run -t sanity -B bench.cfg.example
----

=== Configuring

Configuration files are usually found in the `conf/` directory provided with the dsatest package.

One can use out-of-tree configuration files by using the `-C` or `--conf-dir` flags from the command line.
The specified directory must have the same layout as the default `conf/` directory.
Files found in this alternate directory will have precedence over the default ones.

All configuration files use the INI format.
Three kind of files need to be populated in order to run tests on the bench.
From a bottom-up approach:

switch::
Describe a switch and how its kernel driver exposes some information.
This file can be shared and used in several test benches.
They are located in the `switch/` configuration directory.

target::
Describe the machine being tested, the switches that are on it, and the interfaces that the test bench will be able to use.
This file can also be shared.
They are located in the `target/` configuration directory.

bench::
Describe how the host machine and the target machine are connected to one another.
This file is specific to each bench.

==== Switch

*TODO: Not used yet*

An example switch may look like this:

----
  +----------------+
  |          port0 |----> CPU port
  | SWITCH   port1 |----> User port #0
  |          port2 |----> User port #1
  |          port3 |----> User port #2
  +----------------+
----

See link:conf/switch/example-switch.cfg[].

==== Target

They describe the hardware of the machine being tested.
For instance, consider the following situation:

----
  +--------------------------------------------------+
  |                       TARGET                     |
  |  +----------------+                              |
  |  |          port0 |----> to CPU                  |
  |  | switch0  port1 |--------------------------[ link0 ] <-+
  |  |          port2 |----> Non connected           |       |- connectors
  |  |          port3 |--------------------------[ link1 ] <-+   (eg. RJ45)
  |  +----------------+                              |
  +--------------------------------------------------+
----

Only port1 and port3 of switch0 are connected to front-facing connectors.
Obviously the bench can only use these two ports to run tests.

Describing the internals of the target (which switch port is connected to what front-facing connector) allows to get sensible error reporting if errors occur.
Moreover, these files can be shared by people using the same hardware.

See link:conf/target/example-target.cfg[].

==== Bench

Describe the test bench, i.e. how the controlling machine (aka host), running dsatest, is connected to the target machine.

For instance, let's create a test bench with the target defined in the previous section.
Host and Target are connected with only one cable:

----
  +-------------+                        +---------------+
  |             |         cable          |               |
  |          [ eth8 ]<------------>[ enp0s31f6 ]         |
  |   TARGET    |         link0          |               |
  |          [ eth9 ]                    |      HOST     |
  |             |                        |               |
  +-------------+                        +---------------+
----

Bench configuration file defines that link0 is eth8 on the target side, and enp0s31f6 on host side.
eth9 is left disconnected.
Names of interfaces is defined at the bench level because interfaces may have different names depending on the OS running on it, so it may vary from one test bench to another.

See link:bench.cfg.example[].

When a link is defined under both the host and the target section, dsatest will register that link and the corresponding interfaces so that tests will be able to use them.
Links connected to only one end will be ignored.

==== Configuring the bench

Copy the example bench configuration file and describe your links and how to control your target.
You may have to provide configuration files for your target and switch(es) if they don't exist yet.

[source,sh]
----
cp bench.cfg.example bench.cfg
# edit bench.cfg...
----

== Running the tests

IMPORTANT: You need the `NET_CAP_ADMIN` capability in order to configure network interfaces.

Test cases are usually found in the `tests/` directory provided with the dsatest package.

One can use out-of-tree test files by using the `-T` or `--test-dir` flags from the command line.
The specified directory must have the same layout as the default `tests/` directory.
Files found in this alternate directory will have precedence over the default ones.

=== From the command line

By default, the `dsatest` command runs all the tests found in the test directory.
Run all tests whose method names are prefixed with *test_port_ping*:

[source,sh]
----
./dsatest -t port_ping
----

For details about command line options, see the help message:

[source,sh]
----
./dsatest -h
----

=== From the Python API

Tests are written using unittest, and must respect rules defined by this module.
They can access the test bench instance through the following import:

[source,python]
----
from dsatest.bench import bench
----

API is self-documented in the `sanity.py` test file.

== Authors

dsatest was written by Damien Riegel and other contributors.
It was inspired by *dsa-tests*, written by Andrew Lunn.

== Resources

* link:https://github.com/d-k-c/dsatest[Git source repository on GitHub]
